name: Build with Nuitka

on: 
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            platform: Windows
            arch: x64
            console-mode: disable
          - os: macos-latest
            platform: macOS
            arch: x64
            console-mode: ''
          - os: ubuntu-22.04
            platform: Linux
            arch: x64
            console-mode: ''

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: '2.0'
          script-name: startup.py
          output-filename: "Local Messages Startup"
          windows-console-mode: ${{ matrix.console-mode }}
          mode: standalone
          enable-plugins: tk-inter
          assume-yes-for-downloads: true

      - name: Set artifact name
        id: artifact
        shell: bash
        run: |
          BUILD_NUMBER="${{ github.run_id }}"        
          ARTIFACT_NAME="${{ matrix.platform }} ${{ matrix.arch }} $BUILD_NUMBER"
          echo "display_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          SAFE_NAME="${{ matrix.platform }}_${{ matrix.arch }}_$BUILD_NUMBER"
          echo "safe_name=${SAFE_NAME}" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.display_name }}
          path: build/*.dist/
          include-hidden-files: true
          compression-level: 6
